# Generated by Django 5.2.8 on 2025-11-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('Serialno', models.AutoField(primary_key=True, serialize=False)),
                ('Product_Name', models.CharField(max_length=50)),
                ('Price', models.FloatField()),
                ('Date', models.DateField()),
                ('Style', models.CharField(max_length=10)),
                ('Time', models.TimeField()),
                ('Product_details', models.TextField()),
                ('Quantity', models.IntegerField()),
                ('Expiry_date', models.DateField()),
            ],
        ),
    ]
